### ISSUE TITLE
Console.log statement displaying only the first argument in the output pane when provided with multiple arguments

### ISSUE THREAD

**Issue by gitspeaks** [microsoft/vscode-livepreview#573] opened 2023-12-07 13:36 UTC
Test:

```
<!DOCTYPE html>
<html>
  <body>
    <a id="anchor" href="#">test</a>
    <script>
      var anchorElement = document.getElementById("anchor");

      anchorElement.onclick = function (e) {
        console.log("target: ", e.target.nodeName);
      };
    </script>
  </body>
</html>

```

Actual:

[LOG - 12/07/23 00:00:00] "target: "

Expected (Chrome):

target:  A

**Comment by andreamah** [comment] 2023-12-07 18:04
duplicate of https://github.com/microsoft/vscode-livepreview/issues/163

**Closed by andreamah** 2023-12-07 18:04 UTC
