### ISSUE TITLE
Feature Request: Parallel Scrolling

### ISSUE THREAD

**Issue by abr05** [microsoft/vscode-livepreview#593] opened 2024-01-10 02:47 UTC
A feature that would be extremely helpful is mirrored scrolling - aka, if scrolling in the preview, being able to scroll alongside with that portion of code, or vice versa (selection in the code scrolling to the place of preview). 

This would mimic browser DevTools while having the convenience of your active code editor present for updates and changes.

**Comment by andreamah** [comment] 2024-01-15 23:50
duplicate of https://github.com/microsoft/vscode-livepreview/issues/214

**Closed by andreamah** 2024-01-15 23:50 UTC
