### ISSUE TITLE
Layout issue of the visual viewport in VS Code

### ISSUE THREAD

**Issue by bgillet** [microsoft/vscode-livepreview#500] opened 2023-04-27 15:40 UTC
I am using v0.4.7 of Live Preview in VS Code 1.77.3 on Windows 11.

I was testing an html [sample](https://github.com/WICG/visual-viewport/blob/gh-pages/examples/fixed-to-viewport.html) to understand how meta viewport html tag was working exactly.

I noticed a layout issue of the visual viewport of the live preview frame. As you can see in attached picture, bottom of the live preview frame is slightly overlapped with the status bar.

![image](https://user-images.githubusercontent.com/3019854/234914373-5b097b98-ccc0-4ccb-9a62-38cbe0a6de82.png)

**Comment by andreamah** [comment] 2023-05-02 00:03
I believe this is a duplicate of https://github.com/microsoft/vscode-livepreview/issues/460

**Closed by andreamah** 2023-05-02 00:03 UTC
