### ISSUE TITLE
FR: It would be nice to sync the preview with the code

### ISSUE THREAD

**Issue by sonique6784** [microsoft/vscode-livepreview#642] opened 2024-05-28 11:26 UTC
Feature Request

It would be nice to sync the preview with the code:
- if user scroll in the preview, the code scroll to the same place
- if user click in the preview on the code editor scroll to the right place and highlight the line.

These features are available in "HTML Preview" by "George Oliveira".

**Comment by andreamah** [comment] 2024-06-13 23:36
duplicate of https://github.com/microsoft/vscode-livepreview/issues/214

**Closed by andreamah** 2024-06-13 23:36 UTC
