### ISSUE TITLE
Add command for calling from outside of vscode extensions

### ISSUE THREAD

**Issue by Nightenom** [microsoft/vscode-livepreview#327] opened 2022-09-05 10:14 UTC
Hi, I would like open preview from markdown directly. Now I have to open file first and then preview. It should be possible using <https://code.visualstudio.com/api/extension-guides/command#command-uris>:

Let's have following markdown:
`[tsptwist](./alg-tsptwist/zadani/zadani.html)`
Which I've translated to:
`[tsptwist](command:livePreview.start.internalPreview.atFile?%7B%22file%22%3A%22.%2Falg-tsptwist%2Fzadani%2Fzadani.html%22%7D)`
which is encoded version of:
`command:livePreview.start.internalPreview.atFile?{"file":"./alg-tsptwist/zadani/zadani.html"}`
But for obvious reason (string not being type of vscode.uri) it does literally nothing - no errors anywhere (any logs I've looked into), no action performed

**Comment by andreamah** [comment] 2022-12-09 23:56
duplicate of #388

**Closed by andreamah** 2022-12-09 23:56 UTC
Labels: feature-request
