### ISSUE TITLE
New feature request: please add font scale for better view

### ISSUE THREAD

**Issue by touchft** [microsoft/vscode-livepreview#150] opened 2021-08-25 09:51 UTC
thx

**Comment by Jassi10000** [comment] 2021-08-29 17:27
@misolori Sir , I want to give this issue a shot , can you pls assign me

**Comment by andreamah** [comment] 2022-12-09 17:47
Is this the font scale of the address bar? or scale of the actual content? Content zoom is covered here: #113

**Comment by touchft** [comment] 2022-12-10 08:27
This is for scale of the actual content.

**Comment by andreamah** [comment] 2022-12-12 15:31
duplicate of  #113

**Closed by andreamah** 2022-12-12 15:31 UTC
Labels: feature-request, info-needed
