### ISSUE TITLE
Not working with code-server port proxy

### ISSUE THREAD

**Issue by WifiRouterYT** [microsoft/vscode-livepreview#383] opened 2022-12-07 02:12 UTC
Hey! I just installed code-server for some remote web development via docker, and the docker image automatically enabled port proxying (`domain.com/port/<port>`). I tried running the live preview, but it just gives me a gray screen. Opening the proxied port in a new tab shows that it works fine, though it doesn't update automatically as it would for the desktop version. Is there any workaround for this?

![image](https://user-images.githubusercontent.com/45213292/206070712-502774c8-e583-4c47-b698-e61324984f54.png)
![image](https://user-images.githubusercontent.com/45213292/206070862-d5eb2480-2279-48a7-b1f2-4d1cd4ab7cd1.png)

**Comment by andreamah** [comment] 2022-12-07 16:58
duplicate of #381

**Closed by andreamah** 2022-12-07 16:58 UTC
Labels: duplicate
