### ISSUE TITLE
Live Preview with External Browser Not Launching

### ISSUE THREAD

**Issue by jfcarr** [microsoft/vscode-livepreview#373] opened 2022-10-29 13:53 UTC
I have my Open Preview Target configured as "External Browser".  When I click the "Show Preview" button, nothing happens.  But, if I switch the setting back to "Embedded Preview", it works.  Also, if I _then_ switch the setting to "External Browser" again, it will launch correctly.  Closing and reopening VS Code forces me to go through the same steps again.

Operating System: Ubuntu MATE 22.04
Default browser: Firefox
VS Code version: 1.72.2
Extension version: 0.4.3

**Comment by andreamah** [comment] 2022-10-31 20:40
Duplicate of #367, the fix should be released today on the stable version.

**Closed** 2022-10-31 20:40 UTC
