### ISSUE TITLE
Doesn't recognize Cyrillic in filenames when trying to preview them

### ISSUE THREAD

**Issue by EnoralTheOutCast** [microsoft/vscode-livepreview#243] opened 2022-07-28 05:33 UTC
The title explains itself. When i'm trying to preview a file that contains cyrillic letters in its name, the preview just errors out and tells that file is not found or moved.

**Comment by andreamah** [comment] 2022-07-28 20:13
Duplicate of #131. Unicode file support should be fixed with today's update.

**Closed by andreamah** 2022-07-28 20:13 UTC
Labels: duplicate
