### ISSUE TITLE
Getting 401 unauthorized

### ISSUE THREAD

**Issue by jNullj** [microsoft/vscode-livepreview#364] opened 2022-10-08 15:03 UTC
got a small site with a few js files, im getting 401 unauthorized and only the index.html files seens to load.
this happends on v0.4.2 and preview. when going back to v0.4.1 it works again.

**Comment by andreamah** [comment] 2022-10-11 17:10
Duplicate of #359

**Closed by andreamah** 2022-10-11 17:10 UTC
