### ISSUE TITLE
[Bug]Doesn't work when path contains Chinese characters

### ISSUE THREAD

**Issue by henofdante** [microsoft/vscode-livepreview#224] opened 2022-05-31 11:37 UTC
> File not found
> The file "d:\Code\WebFrontEnd\CSSLearning\03Ã¥Â…ÂƒÃ§Â´Â Ã¦Â˜Â¾Ã§Â¤ÂºÃ¦Â¨Â¡Ã¥Â¼Â.html" cannot be found. It may have been moved, edited, or deleted.

**Comment by Cinux-Chosan** [comment] 2022-06-11 02:30
Same error!

**Comment by andreamah** [comment] 2022-07-27 21:04
Duplicate of #131

**Closed by andreamah** 2022-07-27 21:04 UTC
Labels: duplicate
