### ISSUE TITLE
[Feature request] Server starts silently

### ISSUE THREAD

**Issue by ouweiya** [microsoft/vscode-livepreview#208] opened 2022-03-21 08:39 UTC
It's annoying to automatically start the terminal every time you start the server.

Hopefully a few options might be added:
always start
Start only on errors (startup errors and runtime errors)

![image](https://user-images.githubusercontent.com/28357731/159227140-86ee776c-306d-4f72-9195-37b73762b43d.png)

**Comment by andreamah** [comment] 2022-10-03 16:53
Duplicate of #307

**Closed by andreamah** 2022-10-03 16:53 UTC
Labels: feature-request
