### ISSUE TITLE
PHP support

### ISSUE THREAD

**Issue by NPH12** [microsoft/vscode-livepreview#632] opened 2024-04-09 06:06 UTC
Hi Microsoft
I will really love if preview server has PHP supported. Preview server has everything I need except the PHP support.

I am looking forward to the preview server with PHP support.

Sincerely

Nicolai

**Comment by andreamah** [comment] 2024-04-22 17:23
Duplicate of https://github.com/microsoft/vscode-livepreview/issues/49, please discuss there.

**Closed by andreamah** 2024-04-22 17:23 UTC
