### ISSUE TITLE
SVG live preview

### ISSUE THREAD

**Issue by coliff** [microsoft/vscode-livepreview#138] opened 2021-08-06 02:54 UTC
Not sure if this feature request is outside of the scope for this extension, but I'd love to see a live preview of SVG files like it does with HTML. It'd be useful to be able to see a live preview when making small changes to an SVG such as changing a color etc.

**Comment by anvish2** [comment] 2022-10-24 17:42
Probably it's worth adding file extension setting, so that users can select wich extensions can be live-previewed.

**Comment by andreamah** [comment] 2022-12-07 23:59
duplicate of #89. If I remember correctly, it was mainly because I wanted the extension to be more focused on HTML (plus the other reasons discussed in the issue)

**Closed by andreamah** 2022-12-07 23:59 UTC
Labels: feature-request

**Comment by oliviercailloux** [comment] 2023-10-04 08:01
I hope it is appropriate to indicate a supplementary argument here in favor of supporting SVG preview. I would be happy to use only one extension to preview HTML and SVG files (and other files whose display in a web browser makes sense). 

It would be more efficient to use one extension, whose shortcuts and behavior I know, rather than have to install, configure and getting used to another extension simply because my SVG file happen to not be embedded into an HTML document.

**Comment by bessx** [comment] 2024-01-25 07:21
I have the same issue, would it be possible to have something in the settings to set which extensions Live Preview should run on?  It would be very convenient for a one-click preview of .svg files.
