### ISSUE TITLE
Add Zoom Feature

### ISSUE THREAD

**Issue by MohamedAlkindi** [microsoft/vscode-livepreview#550] opened 2023-09-10 01:00 UTC
Hello, thanks for this lovely extension, I love it so far, and I want to suggest a useful feature to consider, which is the ability to zoom in and out in the preview while not affecting the whole text of the IDE.
Thanks in advance.

**Comment by andreamah** [comment] 2023-09-25 18:13
duplicate of #113

**Closed by andreamah** 2023-09-25 18:13 UTC
