### ISSUE TITLE
Doesn't support favicon

### ISSUE THREAD

**Issue by debjitpal5040** [microsoft/vscode-livepreview#167] opened 2021-10-21 15:26 UTC
This extension is unable to show favicons. Please consider adding this feature. It just shows the below icon for any html page.
<img width="100" alt="Screenshot 2021-10-21 at 20 55 22" src="https://user-images.githubusercontent.com/76846542/138309012-88a6f353-015b-4ca9-a8d3-04d81e234dca.png">

**Comment by andreamah** [comment] 2022-07-29 19:08
Duplicate of #70

**Closed by andreamah** 2022-07-29 19:08 UTC
Labels: duplicate, feature-request
