### ISSUE TITLE
The Ip address cannot use to host server .Using Default IP ****

### ISSUE THREAD

**Issue by Ommmmn** [microsoft/vscode-livepreview#613] opened 2024-02-17 06:29 UTC
![Screenshot 2024-02-17 115838](https://github.com/microsoft/vscode-livepreview/assets/156658127/b55b1408-4e84-4ed5-87c6-04d69a97ac61)

**Comment by rahul-0707** [comment] 2024-03-04 06:22
I'm also facing the same issue...

**Comment by andreamah** [comment] 2024-03-04 18:17
this is a duplicate of https://github.com/microsoft/vscode-livepreview/issues/588. Please see my follow-up there.

**Closed** 2024-03-04 18:18 UTC
