### ISSUE TITLE
it would be nice to add inspect element

### ISSUE THREAD

**Issue by marksamfd** [microsoft/vscode-livepreview#67] opened 2021-07-11 14:51 UTC
by hovering in elements in editor

**Comment by andreamah** [comment] 2022-12-08 00:03
duplicate of #149

**Closed by andreamah** 2022-12-08 00:03 UTC
Labels: feature-request

**Comment by candideu** [comment] 2023-03-17 17:03
If you're still looking for an alternative VS Code extension: [Five Server](https://github.com/yandeu/five-server-vscode) is able to jump to a section of a preview when you double-click or edit a section of your code. It can also highlight the code you are working on in your browser, update your files instantly while typing on your keyboard, and navigate your live preview automatically to the current editing file.

![image](https://raw.githubusercontent.com/yandeu/five-server/main/img/vscode-preview.gif)

Only downside is that there's no Workspace Multi-root support yet.
