### ISSUE TITLE
set Custom External Browser to firefox developer edition

### ISSUE THREAD

**Issue by xtmu** [microsoft/vscode-livepreview#562] opened 2023-11-01 08:23 UTC
I have installed both Firefox and Firefox developer edition, and in Custom External Browser menu there is only one Firefox, how to set alternative Firefox edition?

**Comment by andreamah** [comment] 2023-11-17 18:53
this is a duplicate of https://github.com/microsoft/vscode-livepreview/issues/514

**Closed by andreamah** 2023-11-17 18:53 UTC
