### ISSUE TITLE
Click on tags/elements in HTML and jump to it in HTML document

### ISSUE THREAD

**Issue by bblessatron225** [microsoft/vscode-livepreview#629] opened 2024-03-29 01:52 UTC
Type: <b>Feature Request</b>

FEATURE REQUEST:
Similar to using Brackets, it would be extremely helpful when I'm using Live Preview, if I click on an element or a tag, it would jump to that element and/or highlight the syntax surrounding it.

FEATURE/PERFORMANCE ISSUE:
It's also very annoying when I'm typing and the screen flashes with every update, and sometimes it doesn't even finish the text in the preview until I do something else to force a live preview update.

VS Code version: Code - Insiders 1.88.0-insider (46b756b8434730593b3c911fd1ca43366b29eb03, 2024-03-28T10:54:31.414Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by andreamah** [comment] 2024-04-22 17:15
> Similar to using Brackets, it would be extremely helpful when I'm using Live Preview, if I click on an element or a tag, it would jump to that element and/or highlight the syntax surrounding it.

duplicate of https://github.com/microsoft/vscode-livepreview/issues/214

> It's also very annoying when I'm typing and the screen flashes with every update, and sometimes it doesn't even finish the text in the preview until I do something else to force a live preview update.

You can configure the refresh to happen on every file save instead.
![image](https://github.com/microsoft/vscode-livepreview/assets/31675041/733c464b-faba-425a-9745-4b7a52bd6db3)

**Closed** 2024-10-30 15:19 UTC
Labels: info-needed
