### ISSUE TITLE
The IP address "192.168.XXX.9" cannot be used to host the server. Using default IP 127.0.X.X. 

### ISSUE THREAD

**Issue by vishalsharma123321** [microsoft/vscode-livepreview#621] opened 2024-03-11 16:10 UTC
my live previwe is not working when every i click on it it shows The IP address "192.168.XXX.X" cannot be used to host the server. Using default IP 127.0.X.X. even tho i have changed my ip address in setting and restarted the pc and the vs code several times and also tried to reinstall it and uninstalling it .  currently iam using its v0.5.2024010901 version . please some one help me .

**Comment by andreamah** [comment] 2024-03-11 16:39
this is a duplicate of https://github.com/microsoft/vscode-livepreview/issues/588. Please discuss that there.

**Closed by andreamah** 2024-03-11 16:39 UTC

**Comment by vishalsharma123321** [comment] 2024-03-11 17:09
Thanks for your help but I have already fixed the problem it took nearly 3 and a half hours. I just went to the extension setting and after searching for live preview you will find its setting and find this option which is =  Live Preview: Host IP
The local IP host address to host your files on. here if your IP is good then it will show an extra option the the right side where the Host IP is written. if your IP is not working then you will find the option on the right side of the host IP just lick the extra option and you will find the IP that was showing the error and you have to just reset it. after resting it just uninstall the extension and reinstall it it will work for sure.  if anyone has a problem can reach out to me because I can feel the pain of wasting hours on a simple problem.
